version: "3"

services:
  backtweet_postgres:
    container_name: "backtweet_postgres"
    image: "postgres:9.5"
    volumes: [ "backtweet_postgres:/var/lib/postgresql/data" ]

  backtweet_redis:
    container_name: "backtweet_redis"
    image: "redis:3.2-alpine"
    command: redis-server
    ports: [ "6379:6379" ]
    volumes: [ "backtweet_redis:/var/lib/redis/data" ]

  backtweet_app:
    container_name: "backtweet_app"
    env_file: .env
    depends_on:
      - "backtweet_postgres"
      - "backtweet_redis"
    build: .
    command: bash start.sh
    ports: [ "3000:3000" ]
    volumes:
      - .:/backtweet
      - app-gems:/app-gems

volumes:
  backtweet_postgres:
  backtweet_redis:
  app-gems: